name: Url-Shortener-Api-expressJs
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ..:/workspace:cached # Mount the root folder that contains .git
    networks:
      - url-network
    command: sleep infinity

  postgres:
    image: postgres:latest
    volumes:
      - PgData:/var/lib/postgresql/data
    networks:
      - url-network
    env_file: ../.env.production
    ports:
      - 5432:5432

volumes:
  PgData:

networks:
  url-network:
